### ISSUE TITLE
[feature] Exclude mechanism

### ISSUE THREAD

**Issue by Crystal-RainSlide** [BillDietrich/DecentraleyesSimpler#5]
RT, add an exclude mechanism for the URL Patterns?

**Comment by BillDietrich** [comment]
Added in release 2.0.1, please try it.

I hope I added what you expected.  Basically, there are three cases:

- URL not matched in patterns list: this add-on does nothing, the URL is cached or not with whatever headers it carries.

- URL matched in pattern list but not exclude list: this add-on sets cache time as specified (default 1 month).

- URL matched in patterns list AND exclude list: this add-on does nothing, the URL is cached or not with whatever headers it carries.

**Comment by Crystal-RainSlide** [comment]
It's indeed a typical exclude mechanism. Now pages like unpkg.com/browse/ and:

``` Red
; add / at the end to get a directory listing
https://cdn.jsdelivr.net/npm/jquery/

; (from https://www.jsdelivr.com/)
```

 can be easily excluded.

Rules:
``` JSON
{
	"arrsURLPatterns": [
		"*://unpkg.com/*"
	],
	"arrsExcludeURLPrefixes": [
		"*://cdn.jsdelivr.net/*/",
		"*://unpkg.com/browse/*"
	]
}

```

**Comment by BillDietrich** [comment]
Proper syntax is:

	"arrsExcludeURLPrefixes": [
		"https://cdn.jsdelivr.net/",
		"https://unpkg.com/browse/"
	]

The exclusions are prefixes, not patterns.  Exclusions are not directly supported in the extension API, so I had to implement them differently.

**Comment by Crystal-RainSlide** [comment]
That's all right, thanks for informing!
Then jsDelivr's directory listing can't be exclude by now. Should not be a big issue as those who know about this can use Ctrl + F5 to renew the cache.
